// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbksyregtjyuhayrkexq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFia3N5cmVndGp5dWhheXJrZXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMjM1NzksImV4cCI6MjA2OTg5OTU3OX0.nVk4fcu152hFIrbLv7cjSq3OTvJQB3-ogqUqjBbnvE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});